export const SEED_PACKAGES = [
  // DOMESTIC
  {
    id: 'goa-vibes',
    destination: 'Domestic',
    badge: 'Beach & Nightlife',
    badgeColor: '#2e9e7a',
    category: 'group',
    duration: '4 Days & 3 Nights',
    title: 'Goa Vibes',
    subtitle: 'Sun, Sand & Sea',
    hotels: '3N Beachfront Resort',
    originalPrice: 15000,
    salePrice: 11999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1400&q=85',
    overview: 'Experience the perfect blend of pristine beaches, vibrant nightlife, and Portuguese heritage in Goa. Relax on the golden sands, try thrilling water sports, and enjoy beautiful sunsets.',
    highlights: ['Baga & Calangute Beach', 'Aguada Fort', 'Dudhsagar Waterfalls trip', 'Cruise on Mandovi River'],
    inclusions: ['3 nights accommodation', 'Daily breakfast', 'Airport transfers', 'Sightseeing in AC vehicle'],
    exclusions: ['Flights', 'Meals not mentioned', 'Water sports fees', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival & North Goa Beach Tour', description: 'Arrive in Goa, check in to resort. Evening at Baga Beach.', activities: ['Check-in', 'Beach walk', 'Sunset views'] },
      { day: 2, title: 'South Goa & Heritage', description: 'Visit Basilica of Bom Jesus and Mangueshi Temple. Evening Mandovi River cruise.', activities: ['Old Goa Churches', 'River Cruise'] },
      { day: 3, title: 'Dudhsagar Waterfalls', description: 'Day trip to the majestic Dudhsagar waterfalls and spice plantation.', activities: ['Jeep Safari', 'Waterfall Swim'] },
      { day: 4, title: 'Departure', description: 'Morning at leisure, departure to airport.', activities: ['Breakfast', 'Airport drop'] }
    ]
  },
  {
    id: 'northeast-bliss',
    destination: 'Domestic',
    badge: 'Mountains & Nature',
    badgeColor: '#153e2d',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'North East Bliss',
    subtitle: 'Discover the Unexplored',
    hotels: '2N Gangtok · 2N Darjeeling',
    originalPrice: 22000,
    salePrice: 18999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1400&q=85',
    overview: 'Embark on a mesmerizing journey to the North East. From the majestic tea gardens of Darjeeling to the serene monasteries of Gangtok, witness nature at its finest.',
    highlights: ['Tiger Hill Sunrise', 'Tsomgo Lake', 'Baba Mandir', 'Darjeeling Himalayan Railway (Toy Train)'],
    inclusions: ['4 nights accommodation', 'Breakfast and Dinner', 'All transfers & sightseeing', 'Inner line permits'],
    exclusions: ['Flights/Trains', 'Toy Train tickets', 'Lunch', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Bagdogra -> Gangtok', description: 'Transfer from Bagdogra to Gangtok. Evening free to explore MG Marg.', activities: ['Transfer', 'MG Marg stroll'] },
      { day: 2, title: 'Tsomgo Lake & Baba Mandir', description: 'Full day excursion to the beautiful glacial Tsomgo Lake and Baba Mandir.', activities: ['Tsomgo Lake', 'Baba Mandir'] },
      { day: 3, title: 'Gangtok to Darjeeling', description: 'Transfer to Darjeeling through scenic tea gardens.', activities: ['Scenic drive', 'Tea garden stops'] },
      { day: 4, title: 'Tiger Hill Sunrise & City Tour', description: 'Early morning to Tiger Hill for sunrise. Visit Batasia Loop, Ghoom Monastery.', activities: ['Sunrise', 'Monastery', 'Tea Estate'] },
      { day: 5, title: 'Departure', description: 'Transfer to Bagdogra airport.', activities: ['Breakfast', 'Departure'] }
    ]
  },
  {
    id: 'kerala-gods-own',
    destination: 'Domestic',
    badge: 'Backwaters & Hills',
    badgeColor: '#e8520a',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Kerala God\'s Own Country',
    subtitle: 'Munnar, Thekkady & Alleppey',
    hotels: '2N Munnar · 1N Thekkady · 1N Houseboat',
    originalPrice: 20000,
    salePrice: 16999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1400&q=85',
    overview: 'Experience the best of Kerala in this classic 5-day tour. Enjoy the misty hills of Munnar, wildlife in Thekkady, and a magical overnight stay on a traditional houseboat in Alleppey.',
    highlights: ['Munnar Tea Gardens', 'Periyar Wildlife Sanctuary', 'Alleppey Houseboat Stay', 'Kathakali show'],
    inclusions: ['4 nights stay', 'Breakfast daily (all meals on houseboat)', 'Private AC car', 'Houseboat cruise'],
    exclusions: ['Flights', 'Lunch/Dinner (except houseboat)', 'Entry fees'],
    itinerary: [
      { day: 1, title: 'Kochi to Munnar', description: 'Arrival in Kochi, drive to Munnar enjoying waterfalls on the way.', activities: ['Cheeyappara Falls', 'Check-in'] },
      { day: 2, title: 'Munnar Sightseeing', description: 'Visit Eravikulam National Park, Mattupetty Dam, and Tea Museum.', activities: ['National Park', 'Dam', 'Tea Museum'] },
      { day: 3, title: 'Munnar to Thekkady', description: 'Drive to Thekkady. Optional boat ride in Periyar Lake.', activities: ['Spice Plantation', 'Periyar Lake'] },
      { day: 4, title: 'Thekkady to Alleppey (Houseboat)', description: 'Drive to Alleppey and board your houseboat for a cruise and overnight stay.', activities: ['Backwater cruise', 'Sunset', 'Kerala meals'] },
      { day: 5, title: 'Departure from Kochi', description: 'Morning checkout and drive to Kochi for departure.', activities: ['Checkout', 'Departure'] }
    ]
  },

  // INTERNATIONAL
  {
    id: 'thailand-escape',
    destination: 'International',
    badge: 'Tropical Paradise',
    badgeColor: '#7e5233',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Thailand Escape',
    subtitle: 'Bangkok & Pattaya',
    hotels: '2N Pattaya · 2N Bangkok',
    originalPrice: 35000,
    salePrice: 28999,
    priceNote: 'Per Person (Excl. Flights)',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=85',
    overview: 'Dive into the vibrant culture, stunning beaches, and bustling nightlife of Thailand. From the coral islands of Pattaya to the grand temples and shopping hubs of Bangkok.',
    highlights: ['Coral Island Tour with Lunch', 'Alcazar Show', 'Bangkok City & Temple Tour', 'Shopping at Pratunam'],
    inclusions: ['4 nights accommodation', 'Daily breakfast', 'Airport transfers', 'English speaking guide'],
    exclusions: ['Flights', 'Visa fees', 'Optional tours', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Bangkok -> Pattaya', description: 'Transfer to Pattaya. Evening Alcazar Cabaret Show.', activities: ['Transfer', 'Alcazar Show'] },
      { day: 2, title: 'Coral Island Tour', description: 'Speedboat to Coral Island for water sports and relaxation.', activities: ['Speedboat', 'Water sports', 'Indian Lunch'] },
      { day: 3, title: 'Pattaya to Bangkok', description: 'Transfer to Bangkok. En route Bangkok City & Temple tour.', activities: ['Golden Buddha', 'Marble Temple'] },
      { day: 4, title: 'Leisure in Bangkok', description: 'Free day for shopping or optional Safari World tour.', activities: ['Shopping', 'Street Food'] },
      { day: 5, title: 'Departure', description: 'Transfer to airport for flight back home.', activities: ['Breakfast', 'Departure'] }
    ]
  },
  {
    id: 'dubai-luxury',
    destination: 'International',
    badge: 'Luxury & Adventure',
    badgeColor: '#fbbf24',
    category: 'group',
    duration: '6 Days & 5 Nights',
    title: 'Dubai Luxury',
    subtitle: 'Desert Safari & Burj Khalifa',
    hotels: '5N Premium Hotel in Dubai',
    originalPrice: 45000,
    salePrice: 38999,
    priceNote: 'Per Person (Excl. Flights)',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1400&q=85',
    overview: 'Experience the ultimate luxury in Dubai. From soaring skyscrapers to thrilling desert safaris and endless shopping, Dubai offers an unforgettable modern Arabian adventure.',
    highlights: ['Burj Khalifa 124th Floor', 'Desert Safari with BBQ Dinner', 'Dhow Cruise', 'Dubai Frame'],
    inclusions: ['5 nights hotel stay', 'Daily breakfast', 'Desert Safari', 'Dhow Cruise Dinner', 'Transfers'],
    exclusions: ['Flights', 'Visa', 'Tourism Dirham Fee', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival & Dhow Cruise', description: 'Arrive in Dubai. Evening Dhow Cruise with Marina views and dinner.', activities: ['Check-in', 'Dhow Cruise', 'Dinner'] },
      { day: 2, title: 'Dubai City Tour & Burj Khalifa', description: 'Half day city tour. Evening visit to Burj Khalifa 124th floor.', activities: ['City Tour', 'Dubai Mall', 'Burj Khalifa'] },
      { day: 3, title: 'Desert Safari', description: 'Afternoon Desert Safari with dune bashing, belly dance, and BBQ dinner.', activities: ['Dune Bashing', 'Camel Ride', 'BBQ Dinner'] },
      { day: 4, title: 'Abu Dhabi City Tour', description: 'Full day tour to Abu Dhabi visiting the Grand Mosque.', activities: ['Grand Mosque', 'Ferrari World photo stop'] },
      { day: 5, title: 'Leisure / Shopping', description: 'Free day for shopping in Dubai.', activities: ['Gold Souk', 'Global Village'] },
      { day: 6, title: 'Departure', description: 'Transfer to Dubai Airport.', activities: ['Checkout', 'Departure'] }
    ]
  },

  // SPIRITUAL
  {
    id: 'banaras-mystic',
    destination: 'Spiritual',
    badge: 'Holy City',
    badgeColor: '#e8520a',
    category: 'group',
    duration: '3 Days & 2 Nights',
    title: 'Banaras Mystic',
    subtitle: 'Ghats, Ganga & Spirituality',
    hotels: '2N Heritage Hotel in Varanasi',
    originalPrice: 12000,
    salePrice: 8999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=1400&q=85',
    overview: 'Immerse yourself in the spiritual energy of Varanasi, one of the oldest living cities in the world. Experience the mesmerizing Ganga Aarti and boat rides along the ancient ghats.',
    highlights: ['Evening Ganga Aarti at Dashashwamedh Ghat', 'Morning Boat Ride', 'Kashi Vishwanath Temple', 'Sarnath Visit'],
    inclusions: ['2 nights stay', 'Breakfast', 'Boat ride', 'AC Vehicle for transfers'],
    exclusions: ['Flights/Trains', 'Lunch & Dinner', 'Temple donations', 'Guide fees'],
    itinerary: [
      { day: 1, title: 'Arrival & Ganga Aarti', description: 'Arrive in Varanasi. Evening experience the grand Ganga Aarti.', activities: ['Check-in', 'Ganga Aarti', 'Ghat walk'] },
      { day: 2, title: 'Morning Boat Ride & Sarnath', description: 'Early morning boat ride. Visit Kashi Vishwanath. Afternoon visit Sarnath.', activities: ['Boat Ride', 'Temple Darshan', 'Sarnath Stupa'] },
      { day: 3, title: 'Departure', description: 'Explore local markets. Transfer to airport/station.', activities: ['Shopping', 'Departure'] }
    ]
  },
  {
    id: 'kedarnath-yatra',
    destination: 'Spiritual',
    badge: 'Himalayan Pilgrimage',
    badgeColor: '#153e2d',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Kedarnath Yatra',
    subtitle: 'Journey to Lord Shiva',
    hotels: '1N Haridwar · 2N Guptkashi · 1N Kedarnath',
    originalPrice: 18000,
    salePrice: 14999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1400&q=85',
    overview: 'Embark on a sacred journey to the high-altitude shrine of Kedarnath in the Himalayas. Seek blessings of Lord Shiva amidst breathtaking mountain landscapes.',
    highlights: ['Kedarnath Temple Darshan', 'Ganga Aarti at Har ki Pauri', 'Trek/Helicopter to Kedarnath', 'Scenic Himalayan Drive'],
    inclusions: ['4 nights stay', 'Breakfast & Dinner', 'Transfers from Haridwar/Dehradun'],
    exclusions: ['Helicopter tickets', 'Pony/Palki charges', 'Lunch', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Haridwar Arrival', description: 'Arrive in Haridwar. Evening Ganga Aarti at Har Ki Pauri.', activities: ['Arrival', 'Ganga Aarti'] },
      { day: 2, title: 'Haridwar to Guptkashi', description: 'Scenic drive to Guptkashi along the Mandakini river.', activities: ['Drive', 'Check-in'] },
      { day: 3, title: 'Guptkashi to Kedarnath', description: 'Transfer to Sonprayag/Gaurikund. Trek to Kedarnath. Evening Aarti.', activities: ['Trek/Heli', 'Temple Darshan'] },
      { day: 4, title: 'Kedarnath to Guptkashi', description: 'Morning Darshan. Trek down to Gaurikund and return to Guptkashi.', activities: ['Morning Darshan', 'Trek down'] },
      { day: 5, title: 'Guptkashi to Haridwar', description: 'Drive back to Haridwar for drop-off.', activities: ['Drive', 'Departure'] }
    ]
  }
]
